blocks:
  - name: Step1
    step:
      integration: a570ee3b-ee99-4b10-b8f1-55d1b4a3ea57
      postgres:
        body: |+
          INSERT INTO employee_project (project_id, employee_id)
          VALUES({{Dropdown2.selectedOptionValue}}, {{Dropdown1.selectedOptionValue}});

        operation: run_sql
        usePreparedSql: true
metadata:
  id: f8af7098-45b0-4b46-a8c1-d08883d9112f
  name: API1
  organization: 426c2044-87d3-4a24-8134-cb547602c793
trigger:
  application:
    id: dde3c1a9-57e8-4a41-b8e8-de4a866a4ae0
    pageId: 20e91fb8-f7af-44ed-8c70-e501bac431b3
