blocks:
  - name: Update_Employee_Project
    step:
      integration: a570ee3b-ee99-4b10-b8f1-55d1b4a3ea57
      postgres:
        deletedRows: "{{Table1.editedRows.deletedRows}}"
        insertedRows: "{{Table1.editedRows.insertedRows}}"
        newValues: "{{Table1.editedRows.updatedRows}}"
        operation: update_rows
        schema: public
        table: employee_project
        useAdvancedMatching: auto
metadata:
  id: 309665d4-1698-4839-a046-c83e364808f6
  name: SaveChagesEmployeeProject
  organization: 426c2044-87d3-4a24-8134-cb547602c793
trigger:
  application:
    id: dde3c1a9-57e8-4a41-b8e8-de4a866a4ae0
    pageId: 20e91fb8-f7af-44ed-8c70-e501bac431b3
