blocks:
  - name: Step1
    step:
      integration: a570ee3b-ee99-4b10-b8f1-55d1b4a3ea57
      postgres:
        body: |-
          INSERT INTO timesheet (project_id, employee_id, start_date)
          SELECT 
              {{Dropdown1.selectedOptionValue}}, 
              employee.id, 
              date_trunc('week', now())
          FROM 
              employee
          WHERE 
              employee.superblocks_uuid = {{Global.user.id}};
        operation: run_sql
        usePreparedSql: true
metadata:
  id: 7692883d-a102-4ffa-a801-dad49055e553
  name: AddProject
  organization: 426c2044-87d3-4a24-8134-cb547602c793
trigger:
  application:
    id: dde3c1a9-57e8-4a41-b8e8-de4a866a4ae0
    options:
      executeOnPageLoad: false
    pageId: 6460399c-7139-40f8-89a0-5473a5af766a
