blocks:
  - name: Step1
    step:
      integration: a570ee3b-ee99-4b10-b8f1-55d1b4a3ea57
      postgres:
        body: |-
          SELECT project.*
          from project inner join employee_project on project.id = employee_project.project_id
          inner join employee on employee_project.employee_id = employee.id
          where employee.superblocks_uuid = {{Global.user.id}}
        operation: run_sql
        usePreparedSql: true
metadata:
  id: 4058c6f9-3a86-4be2-bd88-75981f970fb1
  name: GetProjects
  organization: 426c2044-87d3-4a24-8134-cb547602c793
trigger:
  application:
    id: dde3c1a9-57e8-4a41-b8e8-de4a866a4ae0
    options: {}
    pageId: 6460399c-7139-40f8-89a0-5473a5af766a
