blocks:
  - conditional:
      else:
        blocks:
          - name: Step2
            step:
              integration: a570ee3b-ee99-4b10-b8f1-55d1b4a3ea57
              postgres:
                body: |-
                  SELECT timesheet.*
                  from timesheet inner join employee on employee.id = timesheet.employee_id
                  inner join project on project.id = timesheet.project_id
                  where employee."superblocks_uuid" = {{Global.user.id}}
                  and timesheet.start_date = (DATE_TRUNC('week', NOW())::DATE - {{Days.value}}::INTEGER);
                operation: run_sql
                usePreparedSql: true
      elseIf: []
      if:
        blocks:
          - name: Timesheet
            step:
              integration: a570ee3b-ee99-4b10-b8f1-55d1b4a3ea57
              postgres:
                body: |-
                  SELECT timesheet.*
                  from timesheet inner join employee on employee.id = timesheet.employee_id
                  inner join project on project.id = timesheet.project_id
                  where employee."superblocks_uuid" = {{Global.user.id}}
                  and timesheet.start_date = DATE_TRUNC('week', NOW());
                operation: run_sql
                usePreparedSql: true
        condition: "{{Days.value = 0}}"
    name: Condition1
metadata:
  id: ccabd244-f002-4bf4-9fd8-85435e6d3be7
  name: GetTimesheet
  organization: 426c2044-87d3-4a24-8134-cb547602c793
trigger:
  application:
    id: dde3c1a9-57e8-4a41-b8e8-de4a866a4ae0
    options:
      executeOnPageLoad: false
    pageId: 6460399c-7139-40f8-89a0-5473a5af766a
