blocks:
  - name: Step1
    step:
      integration: a570ee3b-ee99-4b10-b8f1-55d1b4a3ea57
      postgres:
        deletedRows: "{{Table1.editedRows.deletedRows}}"
        insertedRows: "{{Table1.editedRows.insertedRows}}"
        newValues: "{{Table1.editedRows.updatedRows}}"
        operation: update_rows
        schema: public
        table: timesheet
        useAdvancedMatching: auto
metadata:
  id: 1626938d-8b9d-439c-bf28-f82b2e4e9e38
  name: CRUDTimesheet
  organization: 426c2044-87d3-4a24-8134-cb547602c793
trigger:
  application:
    id: dde3c1a9-57e8-4a41-b8e8-de4a866a4ae0
    pageId: ffc68f9e-beaf-47bd-8a2c-3ff945bcc0ce
