blocks:
  - name: OnGoingProjectsFromDB
    step:
      integration: a570ee3b-ee99-4b10-b8f1-55d1b4a3ea57
      postgres:
        body: |-
          -- You can use SQL to query data (ex. SELECT * FROM orders;)
          select project.* from project
          inner join employee_project on project.id = employee_project.project_id
          inner join employee on employee_project.employee_id = employee.id
          where employee.superblocks_uuid = {{Global.user.id}}
          	AND project.project_status = 'On Going'
        operation: run_sql
        usePreparedSql: true
metadata:
  id: e1919546-899f-48a7-afb6-f3f1542d1eca
  name: GetOnGoingProjects
  organization: 426c2044-87d3-4a24-8134-cb547602c793
trigger:
  application:
    id: dde3c1a9-57e8-4a41-b8e8-de4a866a4ae0
    pageId: ffc68f9e-beaf-47bd-8a2c-3ff945bcc0ce
