blocks:
  - conditional:
      else:
        blocks:
          - name: return_days
            step:
              integration: javascript
              javascript:
                body: |
                  return Days.value;
      elseIf: []
      if:
        blocks:
          - name: return_0
            step:
              integration: javascript
              javascript:
                body: |
                  return 0;
        condition: '{{Days.value == null || Days.value == ""}}'
    name: Returned_days
  - name: Get_new_start_date
    step:
      integration: javascript
      javascript:
        body: |
          const start_date = new Date() + Returned_days.output;
          console.log(start_date);
          return start_date;
  - name: All_Timesheets_from_start_date
    step:
      integration: a570ee3b-ee99-4b10-b8f1-55d1b4a3ea57
      postgres:
        body: |-
          select DISTINCT * from timesheet
          inner join project on timesheet.project_id = project.id
          inner join employee on timesheet.employee_id = employee.id
          where timesheet.start_date >= {{get_new_start_date.output}}
        operation: run_sql
        usePreparedSql: true
metadata:
  id: 7af64146-a0c7-4709-8840-0307a5929c23
  name: GetTimesheetData
  organization: 426c2044-87d3-4a24-8134-cb547602c793
trigger:
  application:
    id: dde3c1a9-57e8-4a41-b8e8-de4a866a4ae0
    pageId: ffc68f9e-beaf-47bd-8a2c-3ff945bcc0ce
