blocks:
  - name: DaysFromThisWeek
    step:
      integration: javascript
      javascript:
        body: |
          const options = {
            month: "short",
            day: "numeric",
            year: "numeric",
          };
          const curr = new Date();

          //Get the first day of the week
          const first = curr.getDate() - curr.getDay() + 1;

          let days = Array.from(
            { length: 7 },
            (_, i) => new Date(curr.setDate(first + i)),
          );

          days = days.map((date) => moment(date).format("YYYY-MM-DD"));

          console.log("removed time:", days);

          days = days.map((date) => new Date(`${date}T00:00:00.000Z`).toISOString());
          console.log("added null time:", days);
          return days;
  - name: GetFullTimesheet
    step:
      integration: a570ee3b-ee99-4b10-b8f1-55d1b4a3ea57
      postgres:
        body: |-
          select timesheet.id, timesheet.project_id, project.project_name, timesheet.location, timesheet.billable, timesheet.task, timesheet.mon, timesheet.tue, timesheet.wed, timesheet.thu, timesheet.fri, timesheet.sat, timesheet.sun, timesheet.start_date, timesheet.is_leave
          from timesheet
          	inner join employee on employee.id = timesheet.employee_id
          	inner join project on project.id = timesheet.project_id
          where employee.superblocks_uuid = {{Global.user.id}}
          order by timesheet.start_date asc
        operation: run_sql
        usePreparedSql: true
metadata:
  id: 287c09c8-3909-471b-9e90-156142d262f4
  name: GetTimesheets
  organization: 426c2044-87d3-4a24-8134-cb547602c793
trigger:
  application:
    id: dde3c1a9-57e8-4a41-b8e8-de4a866a4ae0
    pageId: ffc68f9e-beaf-47bd-8a2c-3ff945bcc0ce
