blocks:
  - name: UpdateData
    step:
      integration: a570ee3b-ee99-4b10-b8f1-55d1b4a3ea57
      postgres:
        deletedRows: "{{Table1.editedRows.deletedRows}}"
        insertedRows: "{{Table1.editedRows.insertedRows}}"
        newValues: "{{Table1.editedRows.updatedRows}}"
        operation: update_rows
        schema: public
        table: project
        useAdvancedMatching: auto
metadata:
  id: 1b9b109b-c648-4d91-9107-d71094f94811
  name: API2
  organization: 426c2044-87d3-4a24-8134-cb547602c793
trigger:
  application:
    id: dde3c1a9-57e8-4a41-b8e8-de4a866a4ae0
    pageId: 96ca4797-4e1c-4c26-9e82-ac668342c909
