blocks:
  - name: Step1
    step:
      integration: a570ee3b-ee99-4b10-b8f1-55d1b4a3ea57
      postgres:
        body: |-
          -- You can use SQL to query data (ex. SELECT * FROM orders;)
          select * from project
        operation: run_sql
        usePreparedSql: true
metadata:
  id: 1131e00a-b35d-407c-a263-9244bebbedc3
  name: GetProjects
  organization: 426c2044-87d3-4a24-8134-cb547602c793
trigger:
  application:
    id: dde3c1a9-57e8-4a41-b8e8-de4a866a4ae0
    pageId: 96ca4797-4e1c-4c26-9e82-ac668342c909
