blocks:
  - name: UpdateData
    step:
      integration: a570ee3b-ee99-4b10-b8f1-55d1b4a3ea57
      postgres:
        deletedRows: "{{Table1.editedRows.deletedRows}}"
        insertedRows: "{{Table1.editedRows.insertedRows}}"
        newValues: "{{Table1.editedRows.updatedRows}}"
        operation: update_rows
        schema: public
        table: employee
        useAdvancedMatching: auto
metadata:
  id: 17c0ef4f-839f-45a4-a14c-3c0bf99f135c
  name: API1
  organization: 426c2044-87d3-4a24-8134-cb547602c793
trigger:
  application:
    id: dde3c1a9-57e8-4a41-b8e8-de4a866a4ae0
    pageId: 8c423b60-83f1-4b63-9c1f-08a52c02e488
