blocks:
  - name: Step1
    step:
      integration: a570ee3b-ee99-4b10-b8f1-55d1b4a3ea57
      postgres:
        deletedRows: "{{Table2.editedRows.deletedRows}}"
        insertedRows: "{{Table2.editedRows.insertedRows}}"
        newValues: "{{Table2.editedRows.updatedRows}}"
        operation: update_rows
        schema: public
        table: timesheet
        useAdvancedMatching: auto
metadata:
  id: 8b4f4615-34c8-4678-83f7-0f2f26c5e2b0
  name: API2
  organization: 426c2044-87d3-4a24-8134-cb547602c793
trigger:
  application:
    id: dde3c1a9-57e8-4a41-b8e8-de4a866a4ae0
    pageId: 8c423b60-83f1-4b63-9c1f-08a52c02e488
