blocks:
  - name: Step1
    step:
      integration: a570ee3b-ee99-4b10-b8f1-55d1b4a3ea57
      postgres:
        body: select * from employee;
        operation: run_sql
        usePreparedSql: true
metadata:
  id: d7b49789-aae2-460b-97e3-f4b5608cbc1c
  name: GetEmployees
  organization: 426c2044-87d3-4a24-8134-cb547602c793
trigger:
  application:
    id: dde3c1a9-57e8-4a41-b8e8-de4a866a4ae0
    pageId: 8c423b60-83f1-4b63-9c1f-08a52c02e488
