blocks:
  - name: TimesheetData
    step:
      integration: a570ee3b-ee99-4b10-b8f1-55d1b4a3ea57
      postgres:
        body: |-
          select DISTINCT timesheet.* from timesheet
          inner join project on timesheet.project_id = project.id
          where timesheet.employee_id = {{Table1.selectedRow.id}}
        operation: run_sql
        usePreparedSql: true
metadata:
  id: 6a1bd641-ddbe-4ae2-b434-6b3b25adbc2d
  name: GetTimesheetData
  organization: 426c2044-87d3-4a24-8134-cb547602c793
trigger:
  application:
    id: dde3c1a9-57e8-4a41-b8e8-de4a866a4ae0
    options:
      executeOnPageLoad: false
    pageId: 8c423b60-83f1-4b63-9c1f-08a52c02e488
