blocks:
  - name: Step1
    step:
      integration: javascript
      javascript:
        body: |
          /*
           * You can use JavaScript Functions to:
           *   1. Transform the output of previous Steps by referencing their output (ex. Step1.output)
           *   2. Write business logic referencing UI components (ex. Table1.selectedRow.id)
           *   3. Make http calls via axios
           *
           * Learn more in the docs: https://docs.superblocks.com/writing-code/backend-javascript
           */
          const obj = { str: "hello world" };
          console.log(obj.str);
          return obj;
metadata:
  id: 52cbe12a-a302-4144-8021-f022edf50b49
  name: GetWeekDays
  organization: 426c2044-87d3-4a24-8134-cb547602c793
trigger:
  application:
    id: dde3c1a9-57e8-4a41-b8e8-de4a866a4ae0
    pageId: 8c423b60-83f1-4b63-9c1f-08a52c02e488
