blocks:
  - name: Step1
    step:
      integration: python
      python:
        body: |
          # Use Python to:
          #
          # 1. Transform the output of previous Steps by referencing their output (ex. Step1.output)
          # 2. Write logic referencing UI components (ex. Table1.selectedRow.id)
          # 3. Make http calls using requests (import requests)
          #
          # More libraries are coming in the future. Superblocks uses Python 3.

          return {"value": "Hello Superblocks!"}
metadata:
  id: 6d0b7a08-06ce-444c-856c-82f737e17ac4
  name: CalculateProjectAllocations
  organization: 426c2044-87d3-4a24-8134-cb547602c793
trigger:
  application:
    id: dde3c1a9-57e8-4a41-b8e8-de4a866a4ae0
    pageId: 4f77c010-e1b1-404c-a592-2f3252267a92
