blocks:
  - name: Step1
    step:
      integration: a570ee3b-ee99-4b10-b8f1-55d1b4a3ea57
      postgres:
        body: |-
          SELECT (first_name || ' ' || last_name) as full_name  FROM employee
          where superblocks_uuid = {{Global.user.id}};
        operation: run_sql
        usePreparedSql: true
metadata:
  id: 5944cdb1-4e01-44e7-b22a-54369ef74c47
  name: GetUser
  organization: 426c2044-87d3-4a24-8134-cb547602c793
trigger:
  application:
    id: dde3c1a9-57e8-4a41-b8e8-de4a866a4ae0
    pageId: 4f77c010-e1b1-404c-a592-2f3252267a92
