blocks:
  - name: GetFormattedWeekDays
    step:
      integration: javascript
      javascript:
        body: |
          const options = {
            month: "short",
            day: "numeric",
            year: "numeric",
          };
          const curr = new Date();

          //Get the first day of the week
          const first = curr.getDate() - curr.getDay() + 1;

          let days = Array.from({ length: 7 }, (_, i) =>
            new Date(curr.setDate(first + i)).toLocaleDateString("en-US", options),
          );
          console.log(days);
          return days;
metadata:
  id: 106c6a80-67a1-4457-a57d-47850852a8a3
  name: GetWeekDays
  organization: 426c2044-87d3-4a24-8134-cb547602c793
trigger:
  application:
    id: dde3c1a9-57e8-4a41-b8e8-de4a866a4ae0
    pageId: 4f77c010-e1b1-404c-a592-2f3252267a92
